### Delete tasks before user registration
DELETE http://localhost:3000/tasks

### User Registration
POST http://localhost:3000/register
Content-Type: application/json

{
    "username": "example_user",
    "password": "example_password",
    "phoneNumber": "1234567890",
    "priority": 1
}

### User Login
POST http://localhost:3000/login
Content-Type: application/json

{
    "username": "rakesh",
    "password": "rakesh@123"
}

### Create Task
POST http://localhost:3000/tasks
Content-Type: application/json
Authorization: Bearer <access_token>

{
    "title": "Task Title",
    "description": "Task Description",
    "dueDate": "2024-03-26",
    "priority": 1
}

### Get Tasks for Current User
GET http://localhost:3000/tasks
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NWY0MWU3NjQzZjE3NjRhY2NhNDUxZDgiLCJpYXQiOjE3MTA1MDcyMTJ9._tUeqZJCjuiemXOnHLLoHDFD1XcJ_tCTf_UIxUXm1hg

### Create Subtask
POST http://localhost:3000/subtasks
Content-Type: application/json

{
    "task_id": "task_id_here"
}

### Update Task
PUT http://localhost:3000/tasks/:taskId
Content-Type: application/json
Authorization: Bearer <access_token>

{
    "dueDate": "2024-04-10",
    "status": "DONE"
}

### Update Subtask
PUT http://localhost:3000/subtasks/:subtaskId
Content-Type: application/json

{
    "status": 1
}

### Delete Task
DELETE http://localhost:3000/tasks/:taskId
Authorization: Bearer <access_token>

### Get Tasks for Current User with Pagination and Filters
### Get First 'Limit' Tasks for Current User
GET http://localhost:3000/tasks?limit=2&priority=2
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NWY0MWU3NjQzZjE3NjRhY2NhNDUxZDgiLCJpYXQiOjE3MTA1MDcyMTJ9._tUeqZJCjuiemXOnHLLoHDFD1XcJ_tCTf_UIxUXm1hg
